name: Deploy Glue via CloudFormation

on:
  push:
    branches:
      - main  
      - deploy-glue-job
    paths:
      - 'script-path/job-script.py'    
      - 'infra/infra.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SOURCE_S3_PATH: 's3://test-upload-buck/input/test_file.csv'
      TARGET_S3_PATH: 's3://test-upload-buck/output/test_file.parque'
      SCRIPT_LOCATION: 's3://test-upload-buck/script_path/job_script.py'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Upload Glue script to S3
        run: |
          aws s3 cp script-path/job-script.py ${SCRIPT_LOCATION}

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file infra/infra.yaml \
            --stack-name glue-deployment-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              SourceS3Path=${SOURCE_S3_PATH} \
              TargetS3Path=${TARGET_S3_PATH} \
              GlueScriptLocation=${SCRIPT_LOCATION}
